core/urls.py
from django.urls import path,include
from .views import PasswordChangeView
from django.contrib.auth import views as auth_views
from .views import *
from . import views
# import editprofilepageview
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import *

sitemaps = {
    'static': Static_Sitemap,
    'questions': Question_Sitemap,
    'comments': Comment_Sitemap,
    'profiles': Profile_Sitemap,
}


urlpatterns = (
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signup_success', views.handleSignUp, name='signup_success'),
    # activate
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate'),

    path('login_success', views.handleLogin, name="login_success"),

    path('logout/', views.handelLogout, name="handleLogout"),
    # password
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='core/forgot-password.html'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_form.html'), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
         name='password_reset_complete'),
    # notes
    path('edit_profile/<str:username>/', UserEditView.as_view(), name='edit_profile'),

    path('edit_personal_profile/', UserProfileEditView.as_view(), name='edit_profile_personal'),
    # profile
    path('profile/<str:username>/', views.UserProfileView, name='profile'),

    path('notes', views.note, name='notes'),

    path('viewnotes/<int:note_id>', views.viewnotes, name='viewnotes'),

    path('editorjs/', include('django_editorjs_fields.urls')), 
    # search
    path('search', views.search, name='search'),
    # likes
    path('like/<int:note_id>', views.like, name='like'),
    # edit question
    path('question/edit/<int:pk>', UpdatePostView.as_view(), name='edit_question'),

    path('question/delete/<int:pk>', DeletePostView.as_view(), name='delete_question'),
    # comments
    path('comment/edit/<int:pk>', CommentEdit.as_view(), name='comment'),

    path('comment/delete/<int:pk>', CommentDelete.as_view(), name='delete_comment'),
    # password change
    path('password_change/', PasswordsChangeView.as_view(template_name='core/password_change.html'), name='password_change'),
    # for contact
    path('contact/', views.contact_view, name='contact'),
    # sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    # robots.txt
    path('robots.txt', views.robots, name='robots'),
)

gyane/urls.py
from django.contrib import admin
from django.http.response import HttpResponse
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 
from django.conf.urls import url,re_path

def trigger_error(request):
    return HttpResponse('Hello, World!')
urlpatterns = [
    path('gyane_private_admin_no_body_should_know_it/', admin.site.urls),
    path('', include('core.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
    # sentry

]
# urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "core.views.page_not_found_view"

core/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.utils.text import slugify
from django_editorjs_fields import EditorJsJSONField  # Django >= 3.1
from django_editorjs_fields import EditorJsTextField
import core

class UserOTP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_st = models.DateTimeField(auto_now=True)
    otp = models.SmallIntegerField()

# class EditProfileForm(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=200, null=True)
#     email = models.CharField(max_length=200, null=True)
#     # gender = models.CharField(choices=GENDER_CATEGORY,max_length=2)
#     profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
#     bio = MarkdownxField(null=True, blank=True)

#     def __str__(self):
# 	    return self.first_name



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    # import first name from user
    first_name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    small_intro = models.TextField(max_length=100, blank=True, null=True)
    web = models.URLField(max_length=200, blank=True, null=True)
    github_username = models.CharField(max_length=200, blank=True, null=True)
    Twitter_username = models.CharField(max_length=200, blank=True, null=True)
    Facebook_username = models.CharField(max_length=200, blank=True, null=True)
    instagram_username = models.CharField(max_length=200, blank=True, null=True)
    profile_pic = models.ImageField(default="defaultprofile_photo.png", null=True, blank=True)

    
    def __str__(self):
        return str(self.user)
class Question(models.Model):
    note_id = models.AutoField(primary_key=True)
    question =EditorJsJSONField(readOnly=False, autofocus=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_st = models.DateTimeField(auto_now_add=True)
    profile_pic = property(lambda self: self.user.profile.profile_pic)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    views  = models.IntegerField(default=0)
    total_comments = property(lambda self: self.comment_set.count())
    # remove word Comment from comments
    # get the first comment 
    def get_first_comment(self):
        return self.comment_set.all()[:1].get()
    comment = get_first_comment
    # remove word 'Comment' from comment
    


    @property
    def total_likes(self):
        return self.likes.count()
    
    def save(self, *args, **kwargs):
        # self.slug = slugify(self.clean)
        super(Question, self).save(*args, **kwargs)
    
    def __str__(self):
        return 'Question {} by {}'.format(self.question, self.user.username)

class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    comment =  EditorJsJSONField(readOnly=False, autofocus=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    questionid = property(lambda self: self.question_set.note_id)
    time_st = models.DateTimeField(auto_now_add=True)
    views  = models.IntegerField(default=0)
    profile_pic = property(lambda self: self.user.profile.profile_pic)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.comment)
        super(Comment, self).save(*args, **kwargs)
    
    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user.username)

# class Reply(models.Model):
#     reply_id = models.AutoField(primary_key=True)
#     reply = models.TextField(max_length=200, null=True)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
#     time_st = models.DateTimeField(auto_now_add=True)
#     views  = models.IntegerField(default=0)
#     profile_pic = property(lambda self: self.user.profile.profile_pic)
    
#     def save(self, *args, **kwargs):
#         self.slug = slugify(self.reply)
#         super(Reply, self).save(*args, **kwargs)
    
#     def __str__(self):
#         return 'Reply {} by {}'.format(self.reply, self.user.username)
class Updates(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    update_title = models.CharField(max_length=200, null=True)
    update = models.TextField()
    link = models.URLField(max_length=200, null=True)
    time_st = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.update_title

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    email = models.CharField(max_length=100)
    content=models.TextField()
    timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

    def get_object(self):
        return self.email
    def __str__(self):
        return 'Message From '+' - '+self.email

core/forms.py
from dataclasses import field
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django import forms
from .models import *
from django_editorjs_fields import EditorJsWidget

class NoteForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['user', 'slug', 'views', 'time_st', 'note_editorjs_text','likes']
        widgets = {
            'question': EditorJsWidget(config={'minHeight': 100}),
            'question': EditorJsWidget(
                 plugins=[
            "@editorjs/header",
            "@editorjs/image",
            "@editorjs/quote",
            "@editorjs/list",
            "@editorjs/link",
            "@editorjs/code",
            '@editorjs/embed',
            "@editorjs/table@2.0.1",
            "editorjs-hyperlink",
            "@editorjs/inline-code",
            "@editorjs/marker",
        ],
        tools={
            "Hyperlink": {
                "class": "Hyperlink",
                "config": {
                    "shortcut": 'CMD+L',
                    "target": '_blank',
                    "rel": 'nofollow',
                    "availableTargets": ['_blank', '_self'],
                    "availableRels": ['author', 'noreferrer'],
                    "validate": False,
                }
            },
        },
        ),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': EditorJsWidget(config={'minHeight': 100}),
            'comment': EditorJsWidget(
                    plugins=[
                "@editorjs/header",
                "@editorjs/image",
                "@editorjs/quote",
                "@editorjs/list",
                "@editorjs/link",
                "@editorjs/code",
                "@editorjs/embed",
                "@editorjs/table@2.0.1",
            "editorjs-hyperlink",
            "@editorjs/inline-code",
            "@editorjs/marker",
        ],
        tools={
            "Hyperlink": {
                "class": "Hyperlink",
                "config": {
                    "shortcut": 'CMD+L',
                    "target": '_blank',
                    "rel": 'nofollow',
                    "availableTargets": ['_blank', '_self'],
                    "availableRels": ['author', 'noreferrer'],
                    "validate": False,
                }
            },
        },
        ),
        }

# class ReplyForm(forms.ModelForm):
#     class Meta:
#         model = Reply
#         fields = ['reply']
        
class EditProfileForm(forms.ModelForm):
    small_intro = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}), required=False)
    class Meta:
        model = Profile
        fields = ('small_intro','profile_pic','web','github_username','Twitter_username','instagram_username','Facebook_username')

class EditPersonalProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ('email','first_name','last_name','username')

core/templates/core/comment_delete.html
<head>
    <title>Update Question</title>
</head>
{% load static %}
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.3/css/all.css"
integrity="sha384-iKbFRxucmOHIcpWdX9NTZ5WETOPm0Goy0WmfyNcl52qSYtc2Buk0NCe6jU1sWWNB" crossorigin="anonymous">
<link rel="stylesheet" href="{% static '/main.css' %}">
<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet"
href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
<link rel="stylesheet" href="{% static '/assets/fonts/fontawesome-all.min.css' %}">

<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
type="text/css" media="screen" charset="utf-8">
{% include 'core/navbar.html' %}
 <body>
     {% if user.is_authenticated %}
        <h1>Delete Post</h1>
        <br><br>
        <center><div class="form-group cards create-post container col-lg-7 col-sm-8">
            <div class="card__body">
            <form method="POST">
                {% csrf_token %}
               <h1><b> ARE YOU SURE ?</b> </h1><br>
                <button class="btn-primary btn">
                    <!-- delete icon -->
                    <i class="fas fa-trash-alt" style="margin-right: 8px;"></i>Delete</button>
            </form>
        </div>
        </div></center>
       
    {% endif %}
 </body>

core/templates/core/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>{{ user.username }} - Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    <style>
        .list-group-item{
            padding: 0.8rem 1rem !important;
        }
        textarea.form-control {
    min-height: calc(1.5em + 0.75rem + 2px) !important;
}   
.form-control {
    display: block !important;
    font-size: 1rem !important;
    font-weight: 400 !important;
    line-height: 1.5 !important;
    color: #858796 !important;
    background-clip: padding-box !important;
    -moz-appearance: none !important;
    appearance: none !important;
    transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out !important;
}
a{
  text-decoration: none !important;
}
    </style>
<div class="container">
    <div class="main-body">
    
        {% include 'core/navbar.html' %}
{% if user.is_authenticated %}
<form action="" method="POST" enctype="multipart/form-data">
          <!-- /Breadcrumb -->
          <div class="row gutters-sm" style="margin-top: 40px;">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if user.profile.profile_pic.url %}
                    <img src="{{ user.profile.profile_pic.url }}" alt="Admin" class="" style="object-fit: cover;border-radius: 12px;width: 200px;">
                    {% else %}
                    <img src="{% static 'img/defaultprofile_photo.png' %}" alt="Admin" class="rounded-circle" width="150">
                    {% endif %}
                    <div class="mt-3">
                      <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                      <p class="text-secondary mb-1">Gyane-User</p>
                      <p class="text-muted font-size-sm"></p>
                      {% if request.user == user %}
                      <center><input type="file" name="profile_pic" accept="image/*"
                      id="id_profile_pic" class="btn" style="overflow:hidden;width:209px;"></center>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
               
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary"> 
                      {% if user.profile.web %}
                      <a href="{{ user.profile.web }}" target="_blank"> {{ user.profile.web }}</a>
                      <br>
                      <input type="url" name="web" class="vURLField form-control" maxlength="200" id="id_web" value="{{ user.profile.web }}">
                      {% else %}
                      <input type="url" name="web" class="vURLField form-control" maxlength="200" id="id_web" value="{{ user.profile.web }}">
                      {% endif %}
                    </span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                    <span class="text-secondary">
                      {% if user.profile.github_username %}
                      <input type="text" name="github_username" class="vTextField form-control" maxlength="200" id="id_github_username" value="{{ user.profile.github_username }}" placeholder="Link">
                      {% else %}
                      <input type="text" name="github_username" class="vTextField form-control" maxlength="200" id="id_github_username" value="{{ user.profile.github_username }}" placeholder="Link">
                      {% endif %}
                    </span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">
                      {% if user.profile.Twitter_username %}
                      <input type="text" name="Twitter_username" class="vTextField form-control" maxlength="200" id="id_Twitter_username" value="{{ user.profile.Twitter_username }}" placeholder="Link">
                      {% else %}
                      <input type="text" name="Twitter_username" class="vTextField form-control" maxlength="200" id="id_Twitter_username" value="{{ user.profile.Twitter_username }}" placeholder="Link">
                      {% endif %}
                    </span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">
                      {% if user.profile.instagram_username %}
                      <input type="text" name="instagram_username" class="vTextField form-control" maxlength="200" id="id_instagram_username" value="{{ user.profile.instagram_username }}" placeholder="Link">
                      {% else %}
                      <input type="text" name="instagram_username" class="vTextField form-control" maxlength="200" id="id_instagram_username" value="{{ user.profile.instagram_username }}" placeholder="Link">
                      {% endif %}
                    </span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">
                      {% if user.profile.Facebook_username %}
                      <input type="text" name="Facebook_username" class="vTextField form-control" maxlength="200" id="id_Facebook_username" value="{{ user.profile.Facebook_username }}" placeholder="Link">
                      {% else %}
                      <input type="text" name="Facebook_username" class="vTextField form-control" maxlength="200" id="id_Facebook_username" value="{{ user.profile.Facebook_username }}" placeholder="Link">
                      {% endif %}
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ user.username }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full-Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.first_name }} {{ user.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Skills</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      (320) 380-4539
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Short Intro</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ user.profile.small_intro }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-primary " href="/edit_personal_profile">Edit</a>
                      &nbsp;&nbsp;
                      <a class="btn btn-primary " href="/profile/{{ user.username }}">
                        Preview Profile</a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
                
                <div class="col-sm-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                        <div class="mb-3"><label class="form-label" for="id_small_intro"><strong>Short
                            Intro</strong></label><textarea class="form-control"
                        id="id_small_intro" rows="4" placeholder="A few words about you ..."
                        name="small_intro">{{ user.profile.small_intro }}</textarea></div>
                    </div>
                  </div>
                </div>
                {% csrf_token %}
                
                <button class="btn btn-primary" type="submit">Save
                  Settings</button>
                  
           
              </div>
            </div>
          </div>
          
        </div>
    </div>
    <!-- submit button -->
    
  </form >

<style type="text/css">
body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;    
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}

</style>

<script type="text/javascript">

</script>
{% endif %}
</body>
</html>

core/templates/core/forgot-password.html
<!DOCTYPE html>
<html>

<head>
     
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Forgotten Password - GYAN-e</title>
    {% load static %}
    <!-- logo -->
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static '/assets/fonts/fontawesome-all.min.css' %}">
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
               <center> <div class="card shadow-lg o-hidden border-0 my-5 col-lg-8 col-sm-11">
                    <div class="card-body p-0">
                        <div class="row">
                           
                            <div class="">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-2">Forgot Your Password?</h4>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user"  method="POST" >
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <input class="form-control form-control-user" type="email"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address..." name="email">
                                            </div>
                                            <button class="btn btn-primary d-block btn-user w-100" type="submit">Reset
                                            Password</button>
                                    </form>
                                    <div class="text-center">
                                        <hr><a class="small" href="{% url 'signup' %}" style="text-decoration: none;font-weight: 700;">Create an Account!</a>
                                    </div>
                                    <div class="text-center"><a class="small" href="{% url 'home' %}" style="text-decoration: none;font-weight: 700;">Already have an
                                            account? Login!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div></center>
            </div>
        </div>
    </div>
    <script src="{% static '/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/assets/js/script.min.js' %}"></script>
</body>

</html>